# Generated by Django 5.2.5 on 2025-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_thumbnail_alter_project_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
