# Generated by Django 5.2.5 on 2025-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
