# Generated by Django 5.2.5 on 2025-09-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_modified_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='isShared',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
