# Generated by Django 5.2.5 on 2025-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_favorites_project_loves'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remixes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
