# Generated by Django 5.2.5 on 2025-09-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_remixes_project_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
