# Generated by Django 5.2.5 on 2025-09-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_instructions_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shared_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
