# Generated by Django 5.2.5 on 2025-09-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_shared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='shared_at',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.CharField(),
        ),
    ]
