# Generated by Django 5.2.6 on 2025-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_created_at_alter_project_shared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isTrashed',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
