# Generated by Django 5.2.6 on 2025-09-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_istrashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isTrashed',
            field=models.BooleanField(default=False),
        ),
    ]
