# Generated by Django 5.2.6 on 2025-10-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_istrashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isTrashed',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
