# Generated by Django 5.2.6 on 2025-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_backpackitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpackitem',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backpackitem',
            name='asset_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
