# Generated by Django 5.2.6 on 2025-10-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_backpackitem_data_alter_backpackitem_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpackitem',
            name='scripts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backpackitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
