# Generated by Django 5.2.6 on 2025-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('featured', 'Featured'), ('all', 'All'), ('animations', 'Animations'), ('art', 'Art'), ('games', 'Games'), ('music', 'Music'), ('stories', 'Stories'), ('tutorials', 'Tutorials')], default='all', max_length=20),
        ),
    ]
