# Generated by Django 5.2.6 on 2025-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_message_options_remove_message_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('love', 'Love'), ('favorite', 'Favorite'), ('studio_invite', 'Studio Invite'), ('studio_activity', 'Studio Activity'), ('forum_post', 'Forum Post'), ('comment', 'Comment'), ('remix', 'Remix'), ('staff_alert', 'Scratch Team Alert')], max_length=20),
        ),
    ]
