services:
  - type: web
    name: scratchr2-remake
    runtime: python
    repo: https://github.com/CocoBox84/ScratchR2-remake/
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn scratch_clone.wsgi

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: scratch_clone.settings

      - key: PYTHON_VERSION
        value: 3.12

      # Render will auto‑inject DATABASE_URL if you add a PostgreSQL instance
      - key: SECRET_KEY
        generateValue: true